### ISSUE TITLE
How to load CK+ dataset in your code

### ISSUE THREAD

**Issue by fitrialif** [achbogga/Inc_v3_FER#1]
Hi, 

I try to run your code but i doesn't give any output.
I hope you can help me to get run your code.
I using windows with python 3.5 and tensorflow 1.0

**Comment by achbogga** [comment]
Hello, I have been working on other projects for a while. I am back to working on this project now. I can certainly help you with running the code. Can you please elaborate on why it fails? any output perhaps? Thanks

**Comment by achbogga** [comment]
The current pre-release v0.1b can run FER 2013 dataset.  The CK+ dataset preparation and training code will be released in the next version.
