### ISSUE TITLE
Model Weights

### ISSUE THREAD

**Issue by neil454** [achbogga/Inc_v3_FER#2]
Hey there. Any chance you could upload the model weights you've trained? If it doesn't fit in a commit, you can make a new Release and add the weights there.

**Comment by achbogga** [comment]
The previous weights are outdated. I have just started working on this project again. Will update the latest model and weights soon. Thanks for your interest in this project.

**Comment by achbogga** [comment]
I will release the weights in the first release. Please feel free to use the beta release for training yourself. The pre-release v0.1b has the updated version of the code.
